Repository bfoujols/studoo, pull requests merged in 2022-06, with the labels that each got.

#11 #1 implement fichier xlsx
  bin/mstud
  composer.json
  composer.lock
  src/Command/CreateStudentCommand.php
  src/Command/DefaultCommand.php
  src/Service/CommandBanner.php
  src/Service/FileSelect.php
  src/Service/FinderType.php
  src/Service/QuestionType.php
Labels: enhancement

#13 #1 implement fichier xlsx
  README.md
  bin/mstud
  composer.json
  composer.lock
  src/App.php
  src/Command/CreateStudentCommand.php
  src/Command/DefaultCommand.php
  src/Service/CommandBanner.php
  src/Service/FileExtension.php
  src/Service/FileLoader.php
  src/Service/FileSelector.php
  src/Service/FileSource.php
  src/Service/FileType/FileTypeInterface.php
  src/Service/FileType/FileTypeXLSX.php
  src/Service/FinderType.php
  src/Service/QuestionType.php
  tests/data/export-etudiant.ods
  tests/data/export-etudiant.xlsx
Labels: enhancement

#15 Develop->main @Alpha
  .gitignore
  README.md
  src/Command/CreateStudentCommand.php
  src/Entity/Student.php
  src/Service/FileLoader.php
  src/Service/FileModel/FileModel.php
  src/Service/FileModel/FileModelInterface.php
  src/Service/FileModel/FileModelLoadInterface.php
  src/Service/FileModel/FileModelLoadXLSX.php
  src/Service/FileModel/FileModelXLSX_ExportEtudiant.php
  src/Service/FileType/FileTypeXLSX.php
Labels: enhancement

#17 Develop->Main beta@0.1.0
  README.md
  bin/mstud
  src/Command/CreateStudentCommand.php
  src/Command/DefaultCommand.php
  src/Entity/Student.php
  src/Service/CkeckStack.php
  src/Service/DirService.php
  src/Service/NomanclatureService.php
  src/Service/StandardRaw.php
Labels: enhancement

#20 Github Action Codacy
  .github/workflows/codacy.yml
Labels: enhancement

#21 #18 Fix Codacy
  .github/workflows/codacy.yml
  CHANGELOG.md
  README.md
  bin/mstud
  src/App.php
  src/Command/CreateStudentCommand.php
  src/Command/DefaultCommand.php
  src/Service/CkeckStack.php
  src/Service/CommandBanner.php
  src/Service/DirService.php
  src/Service/FileType/FileTypeXLSX.php
  src/Service/FinderType.php
  src/Service/NomanclatureService.php
  src/Service/StandardRaw.php
Labels: bug

#23 #16 #done #comment Add init fichier raw
  ressources/liste-etudiant.xlsx
  src/App.php
  src/Command/CreateFileDefaultCommand.php
Labels: enhancement, good first issue

#24 Main->Develop #16 init Raw
  ressources/liste-etudiant.xlsx
  src/App.php
  src/Command/CreateFileDefaultCommand.php
Labels: enhancement

#27 Develop->Main v0.2.0
  .github/workflows/testing-php80.yml
  .github/workflows/testing-php81.yml
  .github/workflows/testing.yml
  .gitignore
  README.md
  composer.json
  composer.lock
  phpunit.xml
  tests/StudentTest.php
  tests/bootstrap.php
Labels: bug, enhancement

#28 Release v0.2.0-alpha
  CHANGELOG.md
  README.md
  src/App.php
Labels: bug, enhancement

#35 Testing FileExtention:class
  tests/FileExtensionTest.php
Labels: Testing

#37 Test standard row
  tests/Service/StandardRawTest.php
Labels: Testing
